import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const TTSmalls = localFont({
    src: [
        {
            path: '../assets/fonts/TTSmalls-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../assets/fonts/TTSmalls-SemiBold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../assets/fonts/TTSmalls-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
});

export const metadata: Metadata = {
    title: 'The Employee List',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={TTSmalls.className}>{children}</body>
        </html>
    );
}
